version: '3.8'

services:
  calculator-service:
    image: task6.2c
    container_name: task6.2c
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: always